### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by vieirafrancisco** [jailsonsf/ProjExt-web#7]
@jailsonsf, tudo bem?
Acho uma boa você colocar a parte de copiar os dados do arquivo `env.exemple` para o arquivo `.env` e adicionar os comandos para utilizar o Docker/docker-compose (principalmente para rodar o `db`).

**Comment by jailsonsf** [comment]
Olá @vieirafrancisco, acabei de atualizar o readme.
Caso tenha mais alguma informação que precise ser adicionada é só avisar!
